default: &default
  adapter: mysql2
  encoding: utf8

development:
  <<: *default
  database: dev_ramenlog-db

test:
  <<: *default
  database: test_ramenlog-db

production:
  <<: *default
  reconnect: false
  database: ramenlog-db
  pool: 5
  username: admin
  password: boku-ryoma
  socket: /var/lib/mysql/mysql.sock
  host: ramenlog-db.clowxe0fjs0m.ap-northeast-1.rds.amazonaws.com
  database: ramenlog-db
